Further restrict matching of path under .git/annex/objects
- to match a key regex for a directory and the key if deep enough
- to ensure that key and its directory match in name

In the use case of bids metadata extractor seems still insufficient

- in datalad metadata extractor window we get logged

	  File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/bids/layout/index.py", line 193, in _index_dir
		self._index_dir(d, list(config), default_action=default)
	  File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/bids/layout/index.py", line 193, in _index_dir
		self._index_dir(d, list(config), default_action=default)
	  [Previous line repeated 3 more times]
	  File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/bids/layout/index.py", line 163, in _index_dir
		if config_file.exists():
	  File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
		self.stat()
	  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
		return self._accessor.stat(self)
	OSError: [Errno 34] Numerical result out of range: '/tmp/mnt/openneuro/ds000001/.git/annex/objects/Mv/8q/MD5E-s669578--0017a7174b9fdebeb1e57f36027bfb96.nii.gz/layout_config.json'

	> /usr/lib/python3.9/pathlib.py(1232)stat()
	-> return self._accessor.stat(self)

- in datalad fusefs  process we get logged

	[DEBUG  ] /home/yoh/datalad/openneuro/ds000001/.git/annex/objects/Mv/8q/MD5E-s669578--0017a7174b9fdebeb1e57f36027bfb96.nii.gz/layout_config.json: path resolved to .git/annex/objects/Mv/8q/MD5E-s669578--0017a7174b9fdebeb1e57f36027bfb96.nii.gz/layout_config.json in dataset at /home/yoh/datalad/openneuro/ds000001
	[DEBUG  ] .git/annex/objects/Mv/8q/MD5E-s669578--0017a7174b9fdebeb1e57f36027bfb96.nii.gz/layout_config.json: under annex, does not have content
	[DEBUG  ] .git/annex/objects/Mv/8q/MD5E-s669578--0017a7174b9fdebeb1e57f36027bfb96.nii.gz/layout_config.json: opening via fsspec
	[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'whereis', '--key', 'layout_config.json', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true'] (cwd=/home/yoh/datalad/openneuro/ds000001)
	[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'whereis', '--key', 'layout_config.json', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true'] with status 1
	[WARNING] Process <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> was terminated with returncode 1
	[DEBUG  ] Closing stderr of <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...>
	[DEBUG  ] Closing stdin of <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> and waiting process to finish
	[DEBUG  ] Process <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> has finished
	[WARNING] Restarting the process due to previous failure
	[DEBUG  ] Initiating a new process for BatchedAnnex(cmd=<<['git', '-c', ++117 chars++ch']>>, output_proc=<function>, path=<<'/home/yoh/dat++20 chars++001'>>)
	[WARNING] Process <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> was terminated with returncode 1
	[DEBUG  ] Closing stderr of <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...>
	[DEBUG  ] Closing stdin of <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> and waiting process to finish
	[DEBUG  ] Process <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> has finished
	[WARNING] Restarting the process due to previous failure
	[DEBUG  ] Initiating a new process for BatchedAnnex(cmd=<<['git', '-c', ++117 chars++ch']>>, output_proc=<function>, path=<<'/home/yoh/dat++20 chars++001'>>)
	Exception ignored on calling ctypes callback function: functools.partial(<function FUSE._wrapper at 0x7fab1156c280>, <bound method FUSE.getattr of <fuse.FUSE object at 0x7fab10840cd0>>)
	Traceback (most recent call last):
	  File "/home/yoh/proj/datalad/datalad-fuse/venvs/dev3/lib/python3.9/site-packages/fuse.py", line 756, in _wrapper
		self.__critical_exception = e
	NameError: name 'self' is not defined
	fuse: bad error value: 317901728