Inform also under what dataset path we cannot find a url for a key
because otherwise it is hard to impossible to figure out when working on
a hierarchy of datasets, like now the case in dandisets-healthcheck where we
observe following errors:

	Traceback (most recent call last):
	  File "/home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/fuse.py", line 734, in _wrapper
		return func(*args, **kwargs) or 0
	  File "/home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/fuse.py", line 834, in open
		fi.fh = self.operations('open', path.decode(self.encoding),
	  File "/home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/datalad_fuse/fuse_.py", line 75, in __call__
		return super(DataLadFUSE, self).__call__(op, self.root + path, *args)
	  File "/home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/fuse.py", line 1076, in __call__
		return getattr(self, op)(*args)
	  File "/home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/datalad_fuse/fuse_.py", line 214, in open
		fsspec_file = self._adapter.open(path)
	  File "/home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/datalad_fuse/fsspec.py", line 241, in open
		return dsap.open(relpath, mode=mode, encoding=encoding, errors=errors)
	  File "/home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/datalad_fuse/fsspec.py", line 181, in open
		raise IOError(f"Could not find a usable URL for {relpath}")
	OSError: Could not find a usable URL for .git/annex/objects/94/qF/SHA256E-s18769644--a2bb2d0d0c5f094aef3eaa68db4087e2944c0372a015180039d98c94573216b5.nwb/SHA256E-s18769644--a2bb2d0d0c5f094aef3eaa68db4087e2944c0372a015180039d98c94573216b5.nwb

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/fuse.py", line 737, in _wrapper
		if e.errno > 0:
	TypeError: '>' not supported between instances of 'NoneType' and 'int'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
	  File "/home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/fuse.py", line 756, in _wrapper
		self.__critical_exception = e
	NameError: name 'self' is not defined
	fuse: bad error value: -659194720